name: Release Translations
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  process_translations:
    name: Release Translations
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name , 'translations-check-ignore')
    uses: jimmysafe/lokalise-actions/.github/workflows/release.yml@main-v1
    secrets: inherit
