name: Release Translations
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  process_translations:
    name: Release Translations
    if: github.event.pull_request.merged == true
    uses: jimmysafe/lokalise-actions/.github/workflows/release.yml@main-v1
    secrets: inherit
    # with:
    #   lokaliseApiToken: f65180bcef55eb0fa6bc794421b340dc6dbf0569
    #   lokaliseProjectId: 175820916698d77c9ef940.96307178
