name: Task has changed
on:
  workflow_dispatch:
    inputs:
      task_id:
        type: string
        required: true
jobs:
  translation_approval:
    uses: jimmysafe/lokalise-actions/.github/workflows/task-handler.yml@main-v1
    secrets: inherit
    with:
      task_id: ${{ inputs.task_id }}
