name: Task Status Changed
on:
  workflow_dispatch:
    inputs:
      task_id:
        type: string
        required: true
      gh_data:
        type: string
        required: true
jobs:
  tasks_changed:
    uses: jimmysafe/lokalise-actions/.github/workflows/task-status-change.yml@main-v1
    secrets: inherit
    with:
      task_id: ${{ inputs.task_id }}
      gh_data: ${{ inputs.gh_data }}
